<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'usuario_id' => 1,
                'nombre' => 'Balón de Fútbol Adidas',
                'descripcion' => 'Balón oficial en buen estado para entrenamientos y partidos.',
                'precio_venta' => 22.00,
                'precio_alquiler_dia' => 4.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Valencia',
            ],
            [
                'usuario_id' => 1,
                'nombre' => 'Espinilleras Nike',
                'descripcion' => 'Espinilleras ligeras y resistentes.',
                'precio_venta' => 15.00,
                'precio_alquiler_dia' => 2.50,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Valencia',
            ],
            [
                'usuario_id' => 1,
                'nombre' => 'Balón de Baloncesto Spalding',
                'descripcion' => 'Balón indoor/outdoor con buen agarre.',
                'precio_venta' => 25.00,
                'precio_alquiler_dia' => 5.00,
                'vendido' => false,
                'disponible' => false,
                'localidad' => 'Valencia',
            ],
            [
                'usuario_id' => 2,
                'nombre' => 'Raqueta de Tenis Wilson',
                'descripcion' => 'Raqueta ligera ideal para jugadores intermedios.',
                'precio_venta' => 70.00,
                'precio_alquiler_dia' => 8.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Madrid',
            ],
            [
                'usuario_id' => 2,
                'nombre' => 'Pack de pelotas de tenis',
                'descripcion' => 'Bote con pelotas seminuevas.',
                'precio_venta' => 8.00,
                'precio_alquiler_dia' => 1.50,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Madrid',
            ],
            [
                'usuario_id' => 2,
                'nombre' => 'Red de Voleibol portátil',
                'descripcion' => 'Red fácil de montar para playa o pista.',
                'precio_venta' => 55.00,
                'precio_alquiler_dia' => 9.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Madrid',
            ],
            [
                'usuario_id' => 3,
                'nombre' => 'Palos de Golf junior',
                'descripcion' => 'Set de palos de golf para principiantes.',
                'precio_venta' => 120.00,
                'precio_alquiler_dia' => 20.00,
                'vendido' => false,
                'disponible' => false,
                'localidad' => 'Barcelona',
            ],
            [
                'usuario_id' => 3,
                'nombre' => 'Guante de Béisbol Rawlings',
                'descripcion' => 'Guante flexible y cómodo para entrenamiento.',
                'precio_venta' => 30.00,
                'precio_alquiler_dia' => 4.50,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Barcelona',
            ],
            [
                'usuario_id' => 3,
                'nombre' => 'Bate de Béisbol aluminio',
                'descripcion' => 'Bate resistente de tamaño estándar.',
                'precio_venta' => 40.00,
                'precio_alquiler_dia' => 6.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Barcelona',
            ],
            [
                'usuario_id' => 4,
                'nombre' => 'Balón de Rugby Gilbert',
                'descripcion' => 'Balón de rugby para entrenamientos.',
                'precio_venta' => 28.00,
                'precio_alquiler_dia' => 6.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Sevilla',
            ],
            [
                'usuario_id' => 4,
                'nombre' => 'Conos de entrenamiento',
                'descripcion' => 'Pack de conos para ejercicios de agilidad.',
                'precio_venta' => 12.00,
                'precio_alquiler_dia' => 2.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Sevilla',
            ],
            [
                'usuario_id' => 4,
                'nombre' => 'Comba fitness',
                'descripcion' => 'Comba ajustable para entrenamiento cardio.',
                'precio_venta' => 10.00,
                'precio_alquiler_dia' => 1.50,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Sevilla',
            ],
            [
                'usuario_id' => 5,
                'nombre' => 'Mancuernas 10kg',
                'descripcion' => 'Pareja de mancuernas para entrenamiento de fuerza.',
                'precio_venta' => 45.00,
                'precio_alquiler_dia' => 5.50,
                'vendido' => false,
                'disponible' => false,
                'localidad' => 'Bilbao',
            ],
            [
                'usuario_id' => 5,
                'nombre' => 'Esterilla de yoga',
                'descripcion' => 'Esterilla antideslizante en perfecto estado.',
                'precio_venta' => 18.00,
                'precio_alquiler_dia' => 2.50,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Bilbao',
            ],
            [
                'usuario_id' => 5,
                'nombre' => 'Bicicleta estática',
                'descripcion' => 'Bicicleta de interior con resistencia regulable.',
                'precio_venta' => 180.00,
                'precio_alquiler_dia' => 15.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Bilbao',
            ],
            [
                'usuario_id' => 1,
                'nombre' => 'Pack equipamiento deportivo',
                'descripcion' => 'Lote con material variado para entrenamiento.',
                'precio_venta' => 95.00,
                'precio_alquiler_dia' => 15.00,
                'vendido' => false,
                'disponible' => true,
                'localidad' => 'Valencia',
            ],
        ]);
    }
}